-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 02:05:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `NumClient` INT NOT NULL,
  `Prenomclient` VARCHAR(45) NULL,
  `NomClien` VARCHAR(45) NULL,
  `AdresseClient` VARCHAR(45) NULL,
  `VilleClient` VARCHAR(45) NULL,
  `CodePostalClient` VARCHAR(45) NULL,
  `TéléphoneClient` VARCHAR(45) NULL,
  PRIMARY KEY (`NumClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits_has_Catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits_has_Catégorie` (
  `Catégorie_NumCategorie` INT NOT NULL,
  PRIMARY KEY (`Catégorie_NumCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fournisseurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fournisseurs` (
  `NumFournisseur` INT NOT NULL,
  `NomFournisseur` VARCHAR(45) NULL,
  `AdresseFournisseur` VARCHAR(45) NULL,
  `VilleFournisseur` VARCHAR(45) NULL,
  `CodePostalFournisseur` VARCHAR(45) NULL,
  `TelephoneFournisseur` VARCHAR(45) NULL,
  `TelecopieFournisseur` VARCHAR(45) NULL,
  PRIMARY KEY (`NumFournisseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CatalogeFournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CatalogeFournisseur` (
  `Fournisseurs_NumFournisseur` INT NOT NULL,
  PRIMARY KEY (`Fournisseurs_NumFournisseur`),
  INDEX `fk_Produits_has_Fournisseurs_Fournisseurs1_idx` (`Fournisseurs_NumFournisseur` ASC) ,
  CONSTRAINT `fk_Produits_has_Fournisseurs_Fournisseurs1`
    FOREIGN KEY (`Fournisseurs_NumFournisseur`)
    REFERENCES `mydb`.`Fournisseurs` (`NumFournisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits` (
  `NumProduit` INT NOT NULL,
  `NomProduit` VARCHAR(45) NULL,
  `DescriptionProduit` VARCHAR(45) NULL,
  `PrixPublic` DOUBLE NULL,
  `QuantiteEnStock` VARCHAR(45) NULL,
  `Produits_has_Catégorie_Catégorie_NumCategorie` INT NOT NULL,
  `CatalogeFournisseur_Fournisseurs_NumFournisseur` INT NOT NULL,
  PRIMARY KEY (`NumProduit`, `Produits_has_Catégorie_Catégorie_NumCategorie`),
  INDEX `fk_Produits_Produits_has_Catégorie1_idx` (`Produits_has_Catégorie_Catégorie_NumCategorie` ASC) ,
  INDEX `fk_Produits_CatalogeFournisseur1_idx` (`CatalogeFournisseur_Fournisseurs_NumFournisseur` ASC) ,
  CONSTRAINT `fk_Produits_Produits_has_Catégorie1`
    FOREIGN KEY (`Produits_has_Catégorie_Catégorie_NumCategorie`)
    REFERENCES `mydb`.`Produits_has_Catégorie` (`Catégorie_NumCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produits_CatalogeFournisseur1`
    FOREIGN KEY (`CatalogeFournisseur_Fournisseurs_NumFournisseur`)
    REFERENCES `mydb`.`CatalogeFournisseur` (`Fournisseurs_NumFournisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes_has_Salarie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commandes_has_Salarie` (
  `Salarie_NumSalarie` INT NOT NULL,
  PRIMARY KEY (`Salarie_NumSalarie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detail_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detail_commande` (
  `Produits_NumProduit` INT NOT NULL,
  PRIMARY KEY (`Produits_NumProduit`),
  INDEX `fk_Commandes_has_Produits_Produits1_idx` (`Produits_NumProduit` ASC) ,
  CONSTRAINT `fk_Commandes_has_Produits_Produits1`
    FOREIGN KEY (`Produits_NumProduit`)
    REFERENCES `mydb`.`Produits` (`NumProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commandes` (
  `NumCommandes` INT NOT NULL,
  `DateCommandes` DATE NULL,
  `DateExpedition` DATE NULL,
  `NumClient` INT NULL,
  `NumSalarie` INT NULL,
  `Commandes_has_Salarie_Salarie_NumSalarie` INT NOT NULL,
  `Detail_commande_Produits_NumProduit` INT NOT NULL,
  PRIMARY KEY (`NumCommandes`, `Commandes_has_Salarie_Salarie_NumSalarie`, `Detail_commande_Produits_NumProduit`),
  INDEX `fk_Commandes_Commandes_has_Salarie1_idx` (`Commandes_has_Salarie_Salarie_NumSalarie` ASC) ,
  INDEX `fk_Commandes_Detail_commande1_idx` (`Detail_commande_Produits_NumProduit` ASC) ,
  CONSTRAINT `fk_Commandes_Commandes_has_Salarie1`
    FOREIGN KEY (`Commandes_has_Salarie_Salarie_NumSalarie`)
    REFERENCES `mydb`.`Commandes_has_Salarie` (`Salarie_NumSalarie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commandes_Detail_commande1`
    FOREIGN KEY (`Detail_commande_Produits_NumProduit`)
    REFERENCES `mydb`.`Detail_commande` (`Produits_NumProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catégorie` (
  `NumCategorie` INT NOT NULL,
  `DescriptionCategorie` VARCHAR(45) NULL,
  `Produits_has_Catégorie_Catégorie_NumCategorie` INT NOT NULL,
  PRIMARY KEY (`NumCategorie`),
  INDEX `fk_Catégorie_Produits_has_Catégorie1_idx` (`Produits_has_Catégorie_Catégorie_NumCategorie` ASC) ,
  CONSTRAINT `fk_Catégorie_Produits_has_Catégorie1`
    FOREIGN KEY (`Produits_has_Catégorie_Catégorie_NumCategorie`)
    REFERENCES `mydb`.`Produits_has_Catégorie` (`Catégorie_NumCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passer` (
  `Client_NumClient` INT NOT NULL,
  `Commandes_NumCommandes` INT NOT NULL,
  `Commandes_Commandes_has_Salarie_Salarie_NumSalarie` INT NOT NULL,
  PRIMARY KEY (`Client_NumClient`),
  INDEX `fk_Client_has_Commandes_Client_idx` (`Client_NumClient` ASC) ,
  INDEX `fk_Passer_Commandes1_idx` (`Commandes_NumCommandes` ASC, `Commandes_Commandes_has_Salarie_Salarie_NumSalarie` ASC) ,
  CONSTRAINT `fk_Client_has_Commandes_Client`
    FOREIGN KEY (`Client_NumClient`)
    REFERENCES `mydb`.`Client` (`NumClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passer_Commandes1`
    FOREIGN KEY (`Commandes_NumCommandes` , `Commandes_Commandes_has_Salarie_Salarie_NumSalarie`)
    REFERENCES `mydb`.`Commandes` (`NumCommandes` , `Commandes_has_Salarie_Salarie_NumSalarie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salarie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salarie` (
  `NumSalarie` INT NOT NULL,
  `PrenomSalarie` VARCHAR(45) NULL,
  `AdresseSalarie` VARCHAR(45) NULL,
  `VillleSalarie` VARCHAR(45) NULL,
  `CodePostalSalarie` VARCHAR(45) NULL,
  `TelephoneSalarie` VARCHAR(45) NULL,
  `Commandes_has_Salarie_Salarie_NumSalarie` INT NOT NULL,
  PRIMARY KEY (`NumSalarie`, `Commandes_has_Salarie_Salarie_NumSalarie`),
  INDEX `fk_Salarie_Commandes_has_Salarie1_idx` (`Commandes_has_Salarie_Salarie_NumSalarie` ASC) ,
  CONSTRAINT `fk_Salarie_Commandes_has_Salarie1`
    FOREIGN KEY (`Commandes_has_Salarie_Salarie_NumSalarie`)
    REFERENCES `mydb`.`Commandes_has_Salarie` (`Salarie_NumSalarie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
