-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 16:41:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modele
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modele
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modele` DEFAULT CHARACTER SET utf8 ;
USE `modele` ;

-- -----------------------------------------------------
-- Table `modele`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`articles` (
  `idarticles` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(70) NULL,
  `contenu` LONGTEXT NULL,
  `court` LONGTEXT NULL,
  PRIMARY KEY (`idarticles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modele`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`categories` (
  `idcategories` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(70) NULL,
  PRIMARY KEY (`idcategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modele`.`articles_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`articles_categories` (
  `articles_idarticles` INT NOT NULL,
  `categories_idcategories` INT NOT NULL,
  PRIMARY KEY (`articles_idarticles`, `categories_idcategories`),
  INDEX `fk_articles_has_categories_categories1_idx` (`categories_idcategories` ASC) VISIBLE,
  INDEX `fk_articles_has_categories_articles_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_categories_articles`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `modele`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_categories_categories1`
    FOREIGN KEY (`categories_idcategories`)
    REFERENCES `modele`.`categories` (`idcategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modele`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `mot` VARCHAR(70) NULL,
  PRIMARY KEY (`idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modele`.`articles_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`articles_tags` (
  `articles_idarticles` INT NOT NULL,
  `tags_idtags` INT NOT NULL,
  PRIMARY KEY (`articles_idarticles`, `tags_idtags`),
  INDEX `fk_articles_has_tags_tags1_idx` (`tags_idtags` ASC) VISIBLE,
  INDEX `fk_articles_has_tags_articles1_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_articles_has_tags_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `modele`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_tags_tags1`
    FOREIGN KEY (`tags_idtags`)
    REFERENCES `modele`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modele`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`commentaires` (
  `idcommentaires` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(70) NULL,
  `adresse` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `contenu` LONGTEXT NULL,
  `articles_idarticles` INT NOT NULL,
  PRIMARY KEY (`idcommentaires`),
  INDEX `fk_commentaires_articles1_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_commentaires_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `modele`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modele`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modele`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(70) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
