-- MySQL Script generated by MySQL Workbench
-- Thu Feb 20 12:05:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Fidélité`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fidélité` (
  `idFidélité` INT NOT NULL,
  `num_carte` VARCHAR(45) NULL,
  `Points_Fidelité` VARCHAR(45) NULL,
  `Historique_achats` VARCHAR(45) NULL,
  PRIMARY KEY (`idFidélité`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Date_naissance` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NULL,
  `Adresse_mail` VARCHAR(45) NULL,
  `Genre` VARCHAR(45) NULL,
  `Fidélité_idFidélité` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_Fidélité1_idx` (`Fidélité_idFidélité` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Fidélité1`
    FOREIGN KEY (`Fidélité_idFidélité`)
    REFERENCES `mydb`.`Fidélité` (`idFidélité`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `idProduit` INT NOT NULL,
  `NomProduit` VARCHAR(45) NULL,
  `Prix` VARCHAR(45) NULL,
  `Quantité` VARCHAR(45) NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idProduit`),
  INDEX `fk_Produit_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `idFacture` INT NOT NULL,
  `Quantité` VARCHAR(45) NULL,
  `PrixHT` VARCHAR(45) NULL,
  `PrixTTC` VARCHAR(45) NULL,
  `Date_facturation` VARCHAR(45) NULL,
  `Client_idClient` INT NOT NULL,
  `Produit_idProduit` INT NOT NULL,
  PRIMARY KEY (`idFacture`, `Client_idClient`),
  INDEX `fk_Facture_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Facture_Produit1_idx` (`Produit_idProduit` ASC) VISIBLE,
  CONSTRAINT `fk_Facture_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Facture_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `mydb`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT NOT NULL,
  `num_rue` VARCHAR(5) NULL,
  `Rue` VARCHAR(45) NULL,
  `Code_Postal` VARCHAR(5) NULL,
  `Ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client_has_Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client_has_Adresse` (
  `Client_idClient` INT NOT NULL,
  `Adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Adresse_idAdresse`),
  INDEX `fk_Client_has_Adresse_Adresse1_idx` (`Adresse_idAdresse` ASC) VISIBLE,
  INDEX `fk_Client_has_Adresse_Client_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Adresse_Client`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Adresse_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
