-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 18:58:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Musicien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musicien` (
  `Pk_id_musicien` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `nom_de_scene` VARCHAR(45) NULL,
  `nationalite` VARCHAR(45) NULL,
  `date_de_naissance` DATE NULL,
  `date_de_deces` DATE NULL,
  PRIMARY KEY (`Pk_id_musicien`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fonction musicien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fonction musicien` (
  `PK_id_fonction` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_id_fonction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Statistiques du groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Statistiques du groupe` (
  `Pk_id_stats_groupe` INT NOT NULL,
  `nombre_cd_vendus` INT NULL,
  `nombre_concerts` INT NULL,
  `nombre_ecoute_total_sur_plateforme_streaming` INT NULL,
  `annee` INT NULL,
  `source` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_id_stats_groupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groupe` (
  `Pk_id_groupe` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `style_de_musique` VARCHAR(45) NULL,
  `date_formation_du_groupe` DATE NULL,
  `pays_origine` VARCHAR(45) NULL,
  `Fk_id_stats_groupe` INT NOT NULL,
  PRIMARY KEY (`Pk_id_groupe`),
  INDEX `fk_Groupe_Statistiques du groupe_idx` (`Fk_id_stats_groupe` ASC) ,
  CONSTRAINT `fk_Groupe_Statistiques du groupe`
    FOREIGN KEY (`Fk_id_stats_groupe`)
    REFERENCES `mydb`.`Statistiques du groupe` (`Pk_id_stats_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marque` (
  `Pk_id_marque` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `lieu_de_conception` VARCHAR(45) NULL,
  `lieu_de_fabrication` VARCHAR(45) NULL,
  PRIMARY KEY (`Pk_id_marque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type de materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type de materiel` (
  `Pk_id_type_materiel` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `Fk_id_type_materiel` INT NOT NULL,
  INDEX `fk_Type de materiel_Type de materiel1_idx` (`Fk_id_type_materiel` ASC) ,
  PRIMARY KEY (`Pk_id_type_materiel`),
  CONSTRAINT `fk_Type de materiel_Type de materiel1`
    FOREIGN KEY (`Fk_id_type_materiel`)
    REFERENCES `mydb`.`Type de materiel` (`Pk_id_type_materiel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materiel` (
  `Pk_id_materiel` INT NOT NULL,
  `couleur` VARCHAR(45) NULL,
  `reference` VARCHAR(45) NULL,
  `annee_construction` INT NULL,
  `Fk_id_type_materiel` INT NOT NULL,
  `Fk_id_marque` INT NOT NULL,
  PRIMARY KEY (`Pk_id_materiel`),
  INDEX `fk_Materiel_Type de materiel1_idx` (`Fk_id_type_materiel` ASC) ,
  INDEX `fk_Materiel_Marque1_idx` (`Fk_id_marque` ASC) ,
  CONSTRAINT `fk_Materiel_Type de materiel1`
    FOREIGN KEY (`Fk_id_type_materiel`)
    REFERENCES `mydb`.`Type de materiel` (`Pk_id_type_materiel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materiel_Marque1`
    FOREIGN KEY (`Fk_id_marque`)
    REFERENCES `mydb`.`Marque` (`Pk_id_marque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musicien_Groupe`
-- -----------------------------------------------------
CREATE TABLE `Musicien_Groupe` (
  `Fk_id_musicien` INT NOT NULL,
  `Fk_id_groupe` INT NOT NULL,
  `date_debut_activite` DATE NULL,
  `date_fin_activité` DATE NULL,
  `Fk_id_fonction` INT NOT NULL,
  INDEX `fk_Musicien_has_Groupe_Groupe1_idx` (`Fk_id_groupe` ASC) ,
  INDEX `fk_Musicien_has_Groupe_Musicien1_idx` (`Fk_id_musicien` ASC) ,
  INDEX `fk_Musicien_Groupe_Fonction musicien1_idx` (`Fk_id_fonction` ASC),
  CONSTRAINT `fk_Musicien_has_Groupe_Musicien1`
    FOREIGN KEY (`Fk_id_musicien`)
    REFERENCES `mydb`.`Musicien` (`Pk_id_musicien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musicien_has_Groupe_Groupe1`
    FOREIGN KEY (`Fk_id_groupe`)
    REFERENCES `mydb`.`Groupe` (`Pk_id_groupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musicien_Groupe_Fonction musicien1`
    FOREIGN KEY (`Fk_id_fonction`)
    REFERENCES `mydb`.`Fonction musicien` (`PK_id_fonction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musicien_Materiel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musicien_Materiel` (
  `Fk_id_musicien` INT NOT NULL,
  `Fk_id_materiel` INT NOT NULL,
  INDEX `fk_Musicien_has_Materiel_Materiel1_idx` (`Fk_id_materiel` ASC) ,
  INDEX `fk_Musicien_has_Materiel_Musicien1_idx` (`Fk_id_musicien` ASC) ,
  CONSTRAINT `fk_Musicien_has_Materiel_Musicien1`
    FOREIGN KEY (`Fk_id_musicien`)
    REFERENCES `mydb`.`Musicien` (`Pk_id_musicien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Musicien_has_Materiel_Materiel1`
    FOREIGN KEY (`Fk_id_materiel`)
    REFERENCES `mydb`.`Materiel` (`Pk_id_materiel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
