-- MySQL Script generated by MySQL Workbench
-- 02/20/20 12:01:10
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SocCinéma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocCinéma` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SocCinéma` ;

-- -----------------------------------------------------
-- Table `SocCinéma`.`typeFilm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`typeFilm` (
  `idtypeFilm` INT NOT NULL,
  `desTypeFilm` VARCHAR(50) NULL,
  PRIMARY KEY (`idtypeFilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinéma`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`Film` (
  `idFilm` INT NOT NULL,
  `nomFilm` VARCHAR(100) NULL,
  `Durée` TIME NULL,
  `typeFilm_idtypeFilm` INT NOT NULL,
  PRIMARY KEY (`idFilm`, `typeFilm_idtypeFilm`),
  INDEX `fk_Film_typeFilm1_idx` (`typeFilm_idtypeFilm` ASC),
  CONSTRAINT `fk_Film_typeFilm1`
    FOREIGN KEY (`typeFilm_idtypeFilm`)
    REFERENCES `SocCinéma`.`typeFilm` (`idtypeFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinéma`.`Cinéma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`Cinéma` (
  `idSéance` INT NOT NULL,
  `nomCinéma` VARCHAR(100) NULL,
  `Adresse` VARCHAR(200) NULL,
  PRIMARY KEY (`idSéance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinéma`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`Salle` (
  `idSalle` INT NOT NULL,
  `nomSalle` VARCHAR(50) NULL,
  `nbrPlace` INT NULL,
  `Cinéma_idSéance` INT NOT NULL,
  PRIMARY KEY (`idSalle`, `Cinéma_idSéance`),
  INDEX `fk_Salle_Cinéma1_idx` (`Cinéma_idSéance` ASC),
  CONSTRAINT `fk_Salle_Cinéma1`
    FOREIGN KEY (`Cinéma_idSéance`)
    REFERENCES `SocCinéma`.`Cinéma` (`idSéance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinéma`.`Planifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`Planifier` (
  `idPlanifier` INT NOT NULL,
  `Salle_idSalle` INT NOT NULL,
  PRIMARY KEY (`idPlanifier`),
  INDEX `fk_Planifier_Salle1_idx` (`Salle_idSalle` ASC),
  CONSTRAINT `fk_Planifier_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `SocCinéma`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinéma`.`Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`Personnel` (
  `idPersonnel` INT NOT NULL,
  `Nom` VARCHAR(30) NULL,
  `Prénom` VARCHAR(60) NULL,
  `dateNaiss` DATE NULL,
  `Planifier_idPlanifier` INT NOT NULL,
  PRIMARY KEY (`idPersonnel`),
  INDEX `fk_Personnel_Planifier1_idx` (`Planifier_idPlanifier` ASC),
  CONSTRAINT `fk_Personnel_Planifier1`
    FOREIGN KEY (`Planifier_idPlanifier`)
    REFERENCES `SocCinéma`.`Planifier` (`idPlanifier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinéma`.`Affecter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinéma`.`Affecter` (
  `idAffecter` INT NOT NULL,
  `dateDebProj` VARCHAR(45) NULL,
  `dateFinProj` VARCHAR(45) NULL,
  `Salle_idSalle` INT NOT NULL,
  `Personnel_idPersonnel` INT NOT NULL,
  `Film_idFilm` INT NOT NULL,
  `Film_typeFilm_idtypeFilm` INT NOT NULL,
  PRIMARY KEY (`idAffecter`, `Salle_idSalle`, `Personnel_idPersonnel`, `Film_idFilm`, `Film_typeFilm_idtypeFilm`),
  INDEX `fk_Affecter_Salle1_idx` (`Salle_idSalle` ASC),
  INDEX `fk_Affecter_Personnel1_idx` (`Personnel_idPersonnel` ASC),
  INDEX `fk_Affecter_Film1_idx` (`Film_idFilm` ASC, `Film_typeFilm_idtypeFilm` ASC),
  CONSTRAINT `fk_Affecter_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `SocCinéma`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Affecter_Personnel1`
    FOREIGN KEY (`Personnel_idPersonnel`)
    REFERENCES `SocCinéma`.`Personnel` (`idPersonnel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Affecter_Film1`
    FOREIGN KEY (`Film_idFilm` , `Film_typeFilm_idtypeFilm`)
    REFERENCES `SocCinéma`.`Film` (`idFilm` , `typeFilm_idtypeFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
