-- MySQL Script generated by MySQL Workbench
-- 04/22/20 21:18:17
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SocCinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SocCinema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SocCinema` ;

-- -----------------------------------------------------
-- Table `SocCinema`.`typeFilm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`typeFilm` (
  `idtypeFilm` INT NOT NULL,
  `desTypeFilm` VARCHAR(50) NULL,
  PRIMARY KEY (`idtypeFilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`Film` (
  `idFilm` INT NOT NULL,
  `nomFilm` VARCHAR(100) NULL,
  `Duree` TIME NULL,
  `typeFilm_idtypeFilm` INT NOT NULL,
  PRIMARY KEY (`idFilm`, `typeFilm_idtypeFilm`),
  INDEX `fk_Film_typeFilm1_idx` (`typeFilm_idtypeFilm` ASC),
  CONSTRAINT `fk_Film_typeFilm1`
    FOREIGN KEY (`typeFilm_idtypeFilm`)
    REFERENCES `SocCinema`.`typeFilm` (`idtypeFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`Personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`Personnel` (
  `idPersonnel` INT NOT NULL,
  `Nom` VARCHAR(30) NULL,
  `Prenom` VARCHAR(60) NULL,
  `dateNaiss` DATE NULL,
  PRIMARY KEY (`idPersonnel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`Cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`Cinema` (
  `idSeance` INT NOT NULL,
  `nomCinema` VARCHAR(100) NULL,
  `Adresse` VARCHAR(200) NULL,
  PRIMARY KEY (`idSeance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`Salle` (
  `idSalle` INT NOT NULL,
  `nomSalle` VARCHAR(50) NULL,
  `nbrPlace` INT NULL,
  `Cinema_idSeance` INT NOT NULL,
  PRIMARY KEY (`idSalle`, `Cinema_idSeance`),
  INDEX `fk_Salle_Cinema1_idx` (`Cinema_idSeance` ASC),
  CONSTRAINT `fk_Salle_Cinema1`
    FOREIGN KEY (`Cinema_idSeance`)
    REFERENCES `SocCinema`.`Cinema` (`idSeance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`Planifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`Planifier` (
  `idPlanifier` INT NOT NULL,
  `Salle_idSalle` INT NOT NULL,
  PRIMARY KEY (`idPlanifier`),
  INDEX `fk_Planifier_Salle1_idx` (`Salle_idSalle` ASC),
  CONSTRAINT `fk_Planifier_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `SocCinema`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`ReserveSalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`ReserveSalle` (
  `IdReserveSalle` INT NOT NULL,
  `dateDebProj` VARCHAR(45) NULL,
  `dateFinProj` VARCHAR(45) NULL,
  `Salle_idSalle` INT NOT NULL,
  `Film_idFilm` INT NOT NULL,
  PRIMARY KEY (`IdReserveSalle`, `Salle_idSalle`, `Film_idFilm`),
  INDEX `fk_Affecter_Salle1_idx` (`Salle_idSalle` ASC),
  INDEX `fk_Affecter_Film1_idx` (`Film_idFilm` ASC),
  CONSTRAINT `fk_Affecter_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `SocCinema`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Affecter_Film1`
    FOREIGN KEY (`Film_idFilm`)
    REFERENCES `SocCinema`.`Film` (`idFilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SocCinema`.`Affecter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SocCinema`.`Affecter` (
  `idAffecter` INT NOT NULL,
  `ReserveSalle_IdReserveSalle` INT NOT NULL,
  `Personnel_idPersonnel` INT NOT NULL,
  PRIMARY KEY (`idAffecter`, `ReserveSalle_IdReserveSalle`, `Personnel_idPersonnel`),
  INDEX `fk_Affecter_ReserveSalle1_idx` (`ReserveSalle_IdReserveSalle` ASC),
  INDEX `fk_Affecter_Personnel1_idx` (`Personnel_idPersonnel` ASC),
  CONSTRAINT `fk_Affecter_ReserveSalle1`
    FOREIGN KEY (`ReserveSalle_IdReserveSalle`)
    REFERENCES `SocCinema`.`ReserveSalle` (`IdReserveSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Affecter_Personnel1`
    FOREIGN KEY (`Personnel_idPersonnel`)
    REFERENCES `SocCinema`.`Personnel` (`idPersonnel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
