-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 18:47:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CLIENT` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Nom_client` VARCHAR(45) NULL,
  `Prenom_client` VARCHAR(45) NULL,
  `DateNais_client` DATE NULL,
  `Adresse` VARCHAR(200) NULL,
  `Numtel` INT(10) NULL,
  `Mail` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMMANDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMMANDE` (
  `idCOMMANDE` INT NOT NULL AUTO_INCREMENT,
  `Date_commande` DATETIME NULL,
  `Prix_total_cmd` DECIMAL(9,2) NULL,
  `CLIENT_idClient` INT NOT NULL,
  INDEX `fk_COMMANDE_CLIENT_idx` (`CLIENT_idClient` ASC) VISIBLE,
  PRIMARY KEY (`idCOMMANDE`),
  CONSTRAINT `fk_COMMANDE_CLIENT`
    FOREIGN KEY (`CLIENT_idClient`)
    REFERENCES `CLIENT` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRODUIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRODUIT` (
  `idPRODUIT` INT NOT NULL AUTO_INCREMENT,
  `Nom_produit` VARCHAR(45) NULL,
  `Cat_produit` VARCHAR(45) NULL,
  `Prix_unitaire` DECIMAL(9,2) NULL,
  PRIMARY KEY (`idPRODUIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MAGASIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MAGASIN` (
  `idMagasin` INT NOT NULL AUTO_INCREMENT,
  `Nom_magasin` VARCHAR(45) NULL,
  `Adresse_magasin` VARCHAR(200) NULL,
  `CP` VARCHAR(6) NULL,
  `Ville` VARCHAR(45) NULL,
  `Type_magasin` VARCHAR(45) NULL,
  PRIMARY KEY (`idMagasin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DETAILS_COMMANDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DETAILS_COMMANDE` (
  `idDETAILS_COMMANDE` INT NOT NULL AUTO_INCREMENT,
  `Qte_Produit` INT NULL,
  `Prix_total` DECIMAL(9,2) NULL,
  `Date` DATETIME NULL,
  `COMMANDE_idCOMMANDE` INT NOT NULL,
  `PRODUIT_idPRODUIT` INT NOT NULL,
  `MAGASIN_idMagasin` INT NOT NULL,
  PRIMARY KEY (`idDETAILS_COMMANDE`, `COMMANDE_idCOMMANDE`),
  INDEX `fk_DETAILS_COMMANDE_COMMANDE1_idx` (`COMMANDE_idCOMMANDE` ASC) VISIBLE,
  INDEX `fk_DETAILS_COMMANDE_PRODUIT1_idx` (`PRODUIT_idPRODUIT` ASC) VISIBLE,
  INDEX `fk_DETAILS_COMMANDE_MAGASIN1_idx` (`MAGASIN_idMagasin` ASC) VISIBLE,
  CONSTRAINT `fk_DETAILS_COMMANDE_COMMANDE1`
    FOREIGN KEY (`COMMANDE_idCOMMANDE`)
    REFERENCES `COMMANDE` (`idCOMMANDE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETAILS_COMMANDE_PRODUIT1`
    FOREIGN KEY (`PRODUIT_idPRODUIT`)
    REFERENCES `PRODUIT` (`idPRODUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETAILS_COMMANDE_MAGASIN1`
    FOREIGN KEY (`MAGASIN_idMagasin`)
    REFERENCES `MAGASIN` (`idMagasin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
