-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 23:24:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `id` VARCHAR(16) NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `num_ss` INT NULL,
  `date_creation` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`speciality` (
  `titre` VARCHAR(255) NOT NULL,
  `est_medecin` INT NULL,
  `peut_prescrire` INT NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Docteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Docteur` (
  `id` VARCHAR(16) NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `date_creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `secteur` INT NULL,
  `duree_consultation` INT NULL,
  `est_actif` INT NULL,
  `speciality` VARCHAR(255) CHARACTER SET 'DEFAULT' NOT NULL,
  `Docteur_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Docteur_Docteur`
    FOREIGN KEY ()
    REFERENCES `mydb`.`speciality` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`medicaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicaments` (
  `id` VARCHAR(16) NOT NULL,
  `Nom` VARCHAR(255) NULL,
  `posologie` VARCHAR(45) NULL,
  `prix unitaire` INT NULL,
  `est_remboursee` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prescription` (
  `id` VARCHAR(16) NOT NULL,
  `medicaments_id` VARCHAR(16) NOT NULL,
  INDEX `fk_prescription_medicaments1_idx` (`medicaments_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prescription_medicaments1`
    FOREIGN KEY (`medicaments_id`)
    REFERENCES `mydb`.`medicaments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`consultation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultation` (
  `id` VARCHAR(16) NOT NULL,
  `date_creation` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `date_consultation` TIMESTAMP NULL,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  `status` VARCHAR(45) NULL,
  `Patient_id` VARCHAR(16) NOT NULL,
  `Docteur_id` VARCHAR(16) NOT NULL,
  `prescription_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_consultation_Patient1_idx` (`Patient_id` ASC) ,
  INDEX `fk_consultation_Docteur1_idx` (`Docteur_id` ASC) ,
  INDEX `fk_consultation_prescription1_idx` (`prescription_id` ASC) ,
  CONSTRAINT `fk_consultation_Patient1`
    FOREIGN KEY (`Patient_id`)
    REFERENCES `mydb`.`Patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultation_Docteur1`
    FOREIGN KEY (`Docteur_id`)
    REFERENCES `mydb`.`Docteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultation_prescription1`
    FOREIGN KEY (`prescription_id`)
    REFERENCES `mydb`.`prescription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
