-- MySQL Script generated by MySQL Workbench
-- Wed Apr 22 22:33:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema omk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema omk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `omk` DEFAULT CHARACTER SET utf8 ;
USE `omk` ;

-- -----------------------------------------------------
-- Table `omk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(190) NOT NULL,
  `name` VARCHAR(190) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `password_hash` VARCHAR(60) NULL DEFAULT NULL,
  `role` VARCHAR(190) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_8D93D649E7927C74` ON `omk`.`user` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`api_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`api_key` (
  `id` VARCHAR(32) NOT NULL,
  `owner_id` INT(11) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `credential_hash` VARCHAR(60) NOT NULL,
  `last_ip` VARBINARY(16) NULL DEFAULT NULL COMMENT '(DC2Type:ip_address)',
  `last_accessed` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_C912ED9D7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_C912ED9D7E3C61F9` ON `omk`.`api_key` (`owner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`asset` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `media_type` VARCHAR(255) NOT NULL,
  `storage_id` VARCHAR(190) NOT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_2AF5A5C7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_2AF5A5C5CC5DB90` ON `omk`.`asset` (`storage_id` ASC) VISIBLE;

CREATE INDEX `IDX_2AF5A5C7E3C61F9` ON `omk`.`asset` (`owner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`fulltext_search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`fulltext_search` (
  `id` INT(11) NOT NULL,
  `resource` VARCHAR(190) NOT NULL,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `title` LONGTEXT NULL DEFAULT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `resource`),
  CONSTRAINT `FK_AA31FE4A7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_AA31FE4A7E3C61F9` ON `omk`.`fulltext_search` (`owner_id` ASC) VISIBLE;

CREATE FULLTEXT INDEX `IDX_AA31FE4A2B36786B3B8BA7C7` ON `omk`.`fulltext_search` (`title`, `text`) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`vocabulary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`vocabulary` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `namespace_uri` VARCHAR(190) NOT NULL,
  `prefix` VARCHAR(190) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_9099C97B7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_9099C97B9B267FDF` ON `omk`.`vocabulary` (`namespace_uri` ASC) VISIBLE;

CREATE UNIQUE INDEX `UNIQ_9099C97B93B1868E` ON `omk`.`vocabulary` (`prefix` ASC) VISIBLE;

CREATE INDEX `IDX_9099C97B7E3C61F9` ON `omk`.`vocabulary` (`owner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`resource_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`resource_class` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `vocabulary_id` INT(11) NOT NULL,
  `local_name` VARCHAR(190) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_C6F063AD7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_C6F063ADAD0E05F6`
    FOREIGN KEY (`vocabulary_id`)
    REFERENCES `omk`.`vocabulary` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 129
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_C6F063ADAD0E05F6623C14D5` ON `omk`.`resource_class` (`vocabulary_id` ASC, `local_name` ASC) VISIBLE;

CREATE INDEX `IDX_C6F063AD7E3C61F9` ON `omk`.`resource_class` (`owner_id` ASC) VISIBLE;

CREATE INDEX `IDX_C6F063ADAD0E05F6` ON `omk`.`resource_class` (`vocabulary_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`property` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `vocabulary_id` INT(11) NOT NULL,
  `local_name` VARCHAR(190) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_8BF21CDE7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_8BF21CDEAD0E05F6`
    FOREIGN KEY (`vocabulary_id`)
    REFERENCES `omk`.`vocabulary` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 206
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_8BF21CDEAD0E05F6623C14D5` ON `omk`.`property` (`vocabulary_id` ASC, `local_name` ASC) VISIBLE;

CREATE INDEX `IDX_8BF21CDE7E3C61F9` ON `omk`.`property` (`owner_id` ASC) VISIBLE;

CREATE INDEX `IDX_8BF21CDEAD0E05F6` ON `omk`.`property` (`vocabulary_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`resource_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`resource_template` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `resource_class_id` INT(11) NULL DEFAULT NULL,
  `title_property_id` INT(11) NULL DEFAULT NULL,
  `description_property_id` INT(11) NULL DEFAULT NULL,
  `label` VARCHAR(190) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_39ECD52E448CC1BD`
    FOREIGN KEY (`resource_class_id`)
    REFERENCES `omk`.`resource_class` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_39ECD52E724734A3`
    FOREIGN KEY (`title_property_id`)
    REFERENCES `omk`.`property` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_39ECD52E7E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_39ECD52EB84E0D1D`
    FOREIGN KEY (`description_property_id`)
    REFERENCES `omk`.`property` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_39ECD52EEA750E8` ON `omk`.`resource_template` (`label` ASC) VISIBLE;

CREATE INDEX `IDX_39ECD52E7E3C61F9` ON `omk`.`resource_template` (`owner_id` ASC) VISIBLE;

CREATE INDEX `IDX_39ECD52E448CC1BD` ON `omk`.`resource_template` (`resource_class_id` ASC) VISIBLE;

CREATE INDEX `IDX_39ECD52E724734A3` ON `omk`.`resource_template` (`title_property_id` ASC) VISIBLE;

CREATE INDEX `IDX_39ECD52EB84E0D1D` ON `omk`.`resource_template` (`description_property_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`resource` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `resource_class_id` INT(11) NULL DEFAULT NULL,
  `resource_template_id` INT(11) NULL DEFAULT NULL,
  `thumbnail_id` INT(11) NULL DEFAULT NULL,
  `title` LONGTEXT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `resource_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_BC91F41616131EA`
    FOREIGN KEY (`resource_template_id`)
    REFERENCES `omk`.`resource_template` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_BC91F416448CC1BD`
    FOREIGN KEY (`resource_class_id`)
    REFERENCES `omk`.`resource_class` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_BC91F4167E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_BC91F416FDFF2E92`
    FOREIGN KEY (`thumbnail_id`)
    REFERENCES `omk`.`asset` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_BC91F4167E3C61F9` ON `omk`.`resource` (`owner_id` ASC) VISIBLE;

CREATE INDEX `IDX_BC91F416448CC1BD` ON `omk`.`resource` (`resource_class_id` ASC) VISIBLE;

CREATE INDEX `IDX_BC91F41616131EA` ON `omk`.`resource` (`resource_template_id` ASC) VISIBLE;

CREATE INDEX `IDX_BC91F416FDFF2E92` ON `omk`.`resource` (`thumbnail_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`item` (
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_1F1B251EBF396750`
    FOREIGN KEY (`id`)
    REFERENCES `omk`.`resource` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `omk`.`item_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`item_set` (
  `id` INT(11) NOT NULL,
  `is_open` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_1015EEEBF396750`
    FOREIGN KEY (`id`)
    REFERENCES `omk`.`resource` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `omk`.`item_item_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`item_item_set` (
  `item_id` INT(11) NOT NULL,
  `item_set_id` INT(11) NOT NULL,
  PRIMARY KEY (`item_id`, `item_set_id`),
  CONSTRAINT `FK_6D0C9625126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `omk`.`item` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_6D0C9625960278D7`
    FOREIGN KEY (`item_set_id`)
    REFERENCES `omk`.`item_set` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_6D0C9625126F525E` ON `omk`.`item_item_set` (`item_id` ASC) VISIBLE;

CREATE INDEX `IDX_6D0C9625960278D7` ON `omk`.`item_item_set` (`item_set_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`job` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `pid` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `class` VARCHAR(255) NOT NULL,
  `args` LONGTEXT NULL DEFAULT NULL COMMENT '(DC2Type:json_array)',
  `log` LONGTEXT NULL DEFAULT NULL,
  `started` DATETIME NOT NULL,
  `ended` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_FBD8E0F87E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_FBD8E0F87E3C61F9` ON `omk`.`job` (`owner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`media` (
  `id` INT(11) NOT NULL,
  `item_id` INT(11) NOT NULL,
  `ingester` VARCHAR(255) NOT NULL,
  `renderer` VARCHAR(255) NOT NULL,
  `data` LONGTEXT NULL DEFAULT NULL COMMENT '(DC2Type:json_array)',
  `source` LONGTEXT NULL DEFAULT NULL,
  `media_type` VARCHAR(255) NULL DEFAULT NULL,
  `storage_id` VARCHAR(190) NULL DEFAULT NULL,
  `extension` VARCHAR(255) NULL DEFAULT NULL,
  `sha256` CHAR(64) NULL DEFAULT NULL,
  `size` BIGINT(20) NULL DEFAULT NULL,
  `has_original` TINYINT(1) NOT NULL,
  `has_thumbnails` TINYINT(1) NOT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  `lang` VARCHAR(190) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_6A2CA10C126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `omk`.`item` (`id`),
  CONSTRAINT `FK_6A2CA10CBF396750`
    FOREIGN KEY (`id`)
    REFERENCES `omk`.`resource` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_6A2CA10C5CC5DB90` ON `omk`.`media` (`storage_id` ASC) VISIBLE;

CREATE INDEX `IDX_6A2CA10C126F525E` ON `omk`.`media` (`item_id` ASC) VISIBLE;

CREATE INDEX `item_position` ON `omk`.`media` (`item_id` ASC, `position` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`migration` (
  `version` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `omk`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`module` (
  `id` VARCHAR(190) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `omk`.`password_creation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`password_creation` (
  `id` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `activate` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_C77917B4A76ED395`
    FOREIGN KEY (`user_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_C77917B4A76ED395` ON `omk`.`password_creation` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`resource_template_property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`resource_template_property` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `resource_template_id` INT(11) NOT NULL,
  `property_id` INT(11) NOT NULL,
  `alternate_label` VARCHAR(255) NULL DEFAULT NULL,
  `alternate_comment` LONGTEXT NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  `data_type` VARCHAR(255) NULL DEFAULT NULL,
  `is_required` TINYINT(1) NOT NULL,
  `is_private` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_4689E2F116131EA`
    FOREIGN KEY (`resource_template_id`)
    REFERENCES `omk`.`resource_template` (`id`),
  CONSTRAINT `FK_4689E2F1549213EC`
    FOREIGN KEY (`property_id`)
    REFERENCES `omk`.`property` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_4689E2F116131EA549213EC` ON `omk`.`resource_template_property` (`resource_template_id` ASC, `property_id` ASC) VISIBLE;

CREATE INDEX `IDX_4689E2F116131EA` ON `omk`.`resource_template_property` (`resource_template_id` ASC) VISIBLE;

CREATE INDEX `IDX_4689E2F1549213EC` ON `omk`.`resource_template_property` (`property_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`session` (
  `id` VARCHAR(190) NOT NULL,
  `data` LONGBLOB NOT NULL,
  `modified` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `omk`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`setting` (
  `id` VARCHAR(190) NOT NULL,
  `value` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `omk`.`site_page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site_page` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site_id` INT(11) NOT NULL,
  `slug` VARCHAR(190) NOT NULL,
  `title` VARCHAR(190) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_2F900BD9F6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `omk`.`site` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_2F900BD9F6BD1646989D9B62` ON `omk`.`site_page` (`site_id` ASC, `slug` ASC) VISIBLE;

CREATE INDEX `IDX_2F900BD9F6BD1646` ON `omk`.`site_page` (`site_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `homepage_id` INT(11) NULL DEFAULT NULL,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `slug` VARCHAR(190) NOT NULL,
  `theme` VARCHAR(190) NOT NULL,
  `title` VARCHAR(190) NOT NULL,
  `summary` LONGTEXT NULL DEFAULT NULL,
  `navigation` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  `item_pool` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_694309E4571EDDA`
    FOREIGN KEY (`homepage_id`)
    REFERENCES `omk`.`site_page` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_694309E47E3C61F9`
    FOREIGN KEY (`owner_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_694309E4989D9B62` ON `omk`.`site` (`slug` ASC) VISIBLE;

CREATE UNIQUE INDEX `UNIQ_694309E4571EDDA` ON `omk`.`site` (`homepage_id` ASC) VISIBLE;

CREATE INDEX `IDX_694309E47E3C61F9` ON `omk`.`site` (`owner_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`site_page_block`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site_page_block` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `page_id` INT(11) NOT NULL,
  `layout` VARCHAR(80) NOT NULL,
  `data` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_C593E731C4663E4`
    FOREIGN KEY (`page_id`)
    REFERENCES `omk`.`site_page` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_C593E731C4663E4` ON `omk`.`site_page_block` (`page_id` ASC) VISIBLE;

CREATE INDEX `page_position` ON `omk`.`site_page_block` (`page_id` ASC, `position` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`site_block_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site_block_attachment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `block_id` INT(11) NOT NULL,
  `item_id` INT(11) NULL DEFAULT NULL,
  `media_id` INT(11) NULL DEFAULT NULL,
  `caption` LONGTEXT NOT NULL,
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_236473FE126F525E`
    FOREIGN KEY (`item_id`)
    REFERENCES `omk`.`item` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `FK_236473FEE9ED820C`
    FOREIGN KEY (`block_id`)
    REFERENCES `omk`.`site_page_block` (`id`),
  CONSTRAINT `FK_236473FEEA9FDD75`
    FOREIGN KEY (`media_id`)
    REFERENCES `omk`.`media` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_236473FEE9ED820C` ON `omk`.`site_block_attachment` (`block_id` ASC) VISIBLE;

CREATE INDEX `IDX_236473FE126F525E` ON `omk`.`site_block_attachment` (`item_id` ASC) VISIBLE;

CREATE INDEX `IDX_236473FEEA9FDD75` ON `omk`.`site_block_attachment` (`media_id` ASC) VISIBLE;

CREATE INDEX `block_position` ON `omk`.`site_block_attachment` (`block_id` ASC, `position` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`site_item_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site_item_set` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site_id` INT(11) NOT NULL,
  `item_set_id` INT(11) NOT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_D4CE134960278D7`
    FOREIGN KEY (`item_set_id`)
    REFERENCES `omk`.`item_set` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_D4CE134F6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `omk`.`site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_D4CE134F6BD1646960278D7` ON `omk`.`site_item_set` (`site_id` ASC, `item_set_id` ASC) VISIBLE;

CREATE INDEX `IDX_D4CE134F6BD1646` ON `omk`.`site_item_set` (`site_id` ASC) VISIBLE;

CREATE INDEX `IDX_D4CE134960278D7` ON `omk`.`site_item_set` (`item_set_id` ASC) VISIBLE;

CREATE INDEX `position` ON `omk`.`site_item_set` (`position` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`site_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `site_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `role` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_C0401D6FA76ED395`
    FOREIGN KEY (`user_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_C0401D6FF6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `omk`.`site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `UNIQ_C0401D6FF6BD1646A76ED395` ON `omk`.`site_permission` (`site_id` ASC, `user_id` ASC) VISIBLE;

CREATE INDEX `IDX_C0401D6FF6BD1646` ON `omk`.`site_permission` (`site_id` ASC) VISIBLE;

CREATE INDEX `IDX_C0401D6FA76ED395` ON `omk`.`site_permission` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`site_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`site_setting` (
  `id` VARCHAR(190) NOT NULL,
  `site_id` INT(11) NOT NULL,
  `value` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  PRIMARY KEY (`id`, `site_id`),
  CONSTRAINT `FK_64D05A53F6BD1646`
    FOREIGN KEY (`site_id`)
    REFERENCES `omk`.`site` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_64D05A53F6BD1646` ON `omk`.`site_setting` (`site_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`user_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`user_setting` (
  `id` VARCHAR(190) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `value` LONGTEXT NOT NULL COMMENT '(DC2Type:json_array)',
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `FK_C779A692A76ED395`
    FOREIGN KEY (`user_id`)
    REFERENCES `omk`.`user` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_C779A692A76ED395` ON `omk`.`user_setting` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `omk`.`value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omk`.`value` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `resource_id` INT(11) NOT NULL,
  `property_id` INT(11) NOT NULL,
  `value_resource_id` INT(11) NULL DEFAULT NULL,
  `type` VARCHAR(255) NOT NULL,
  `lang` VARCHAR(255) NULL DEFAULT NULL,
  `value` LONGTEXT NULL DEFAULT NULL,
  `uri` LONGTEXT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_1D7758344BC72506`
    FOREIGN KEY (`value_resource_id`)
    REFERENCES `omk`.`resource` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_1D775834549213EC`
    FOREIGN KEY (`property_id`)
    REFERENCES `omk`.`property` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_1D77583489329D25`
    FOREIGN KEY (`resource_id`)
    REFERENCES `omk`.`resource` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `IDX_1D77583489329D25` ON `omk`.`value` (`resource_id` ASC) VISIBLE;

CREATE INDEX `IDX_1D775834549213EC` ON `omk`.`value` (`property_id` ASC) VISIBLE;

CREATE INDEX `IDX_1D7758344BC72506` ON `omk`.`value` (`value_resource_id` ASC) VISIBLE;

CREATE INDEX `value` ON `omk`.`value` (`value`(190) ASC) VISIBLE;

CREATE INDEX `uri` ON `omk`.`value` (`uri`(190) ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
