-- MySQL Script generated by MySQL Workbench
-- Thu Feb 20 12:04:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Eleves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eleves` (
  `idEleves` INT NOT NULL,
  `Nom` CHAR(255) NULL,
  `Prenom` CHAR(255) NULL,
  `Adresse` CHAR(255) NULL,
  `CP` INT(5) NULL,
  `Ville` CHAR(255) NULL,
  PRIMARY KEY (`idEleves`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moniteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moniteur` (
  `idMoniteur` INT NOT NULL,
  `Nom_moniteur` CHAR(255) NULL,
  `Prenom_moniteur` CHAR(255) NULL,
  `Date_naissance` DATE NULL,
  `Sexe` CHAR(1) NULL,
  PRIMARY KEY (`idMoniteur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voiture` (
  `idVoiture` INT NOT NULL,
  `Num_imatriculation` VARCHAR(9) NULL,
  `Modele` CHAR(50) NULL,
  `couleur` CHAR(50) NULL,
  `date_mise_circulation` DATE NULL,
  PRIMARY KEY (`idVoiture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecon` (
  `idLecon` INT NOT NULL,
  `idMoniteur` INT NOT NULL,
  `idVoiture` INT NOT NULL,
  `Date_lecon` DATE NULL,
  PRIMARY KEY (`idLecon`, `idMoniteur`, `idVoiture`),
  INDEX `fk_Lecon_Moniteur1_idx` (`idMoniteur` ASC),
  INDEX `fk_Lecon_Voiture1_idx` (`idVoiture` ASC),
  CONSTRAINT `fk_Lecon_Moniteur1`
    FOREIGN KEY (`idMoniteur`)
    REFERENCES `mydb`.`Moniteur` (`idMoniteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lecon_Voiture1`
    FOREIGN KEY (`idVoiture`)
    REFERENCES `mydb`.`Voiture` (`idVoiture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecon_has_Eleves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecon_has_Eleves` (
  `Lecon_idLecon` INT NOT NULL,
  `Eleves_idEleves` INT NOT NULL,
  PRIMARY KEY (`Lecon_idLecon`, `Eleves_idEleves`),
  INDEX `fk_Lecon_has_Eleves_Eleves1_idx` (`Eleves_idEleves` ASC),
  INDEX `fk_Lecon_has_Eleves_Lecon1_idx` (`Lecon_idLecon` ASC),
  CONSTRAINT `fk_Lecon_has_Eleves_Lecon1`
    FOREIGN KEY (`Lecon_idLecon`)
    REFERENCES `mydb`.`Lecon` (`idLecon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lecon_has_Eleves_Eleves1`
    FOREIGN KEY (`Eleves_idEleves`)
    REFERENCES `mydb`.`Eleves` (`idEleves`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eleves_has_Lecon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eleves_has_Lecon` (
  `Eleves_id` INT NOT NULL,
  `Lecon_id` INT NOT NULL,
  PRIMARY KEY (`Eleves_id`, `Lecon_id`),
  INDEX `fk_Eleves_has_Lecon_Lecon1_idx` (`Lecon_id` ASC),
  INDEX `fk_Eleves_has_Lecon_Eleves1_idx` (`Eleves_id` ASC),
  CONSTRAINT `fk_Eleves_has_Lecon_Eleves1`
    FOREIGN KEY (`Eleves_id`)
    REFERENCES `mydb`.`Eleves` (`idEleves`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Eleves_has_Lecon_Lecon1`
    FOREIGN KEY (`Lecon_id`)
    REFERENCES `mydb`.`Lecon` (`idLecon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
