-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 09:28:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `mydb`.`LOGEMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOGEMENT` (
  `LOG_ID` INT NOT NULL AUTO_INCREMENT,
  `LOG_TYPE` VARCHAR(32) NULL,
  `LOG_ADRESSE` TEXT NULL,
  `LOG_BAIN` INT NULL,
  `LOG_DOUCHE` INT NULL,
  `LOG_WC` INT NULL,
  `LOG_COUCHAGE` SMALLINT(2) NULL,
  `LOG_INTERNET` CHAR(3) NULL,
  `LOG_AUTRES_EQUIPEMENTS` TEXT NULL,
  PRIMARY KEY (`LOG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PLANNING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PLANNING` (
  `PLN_JOUR` DATE NOT NULL,
  PRIMARY KEY (`PLN_JOUR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOG_PLN_CLI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOG_PLN_CLI` (
  `CLI_ID` INT NOT NULL,
  `PLN_JOUR` DATE NOT NULL,
  `LOG_ID` INT NOT NULL,
  `LOG_PLN_CLI_NB_PERS` SMALLINT NULL,
  `LOG_PLN_CLI_RESERVE` INT(2) NULL,
  `LOG_PLN_CLI_OCCUPE` INT(2) NULL,
  PRIMARY KEY (`CLI_ID`, `PLN_JOUR`, `LOG_ID`),
  INDEX `fk_LOG_PLN_CLI_PLANNING1_idx` (`PLN_JOUR` ASC),
  INDEX `fk_LOG_PLN_CLI_LOGEMENT1_idx` (`LOG_ID` ASC),
  CONSTRAINT `fk_LOG_PLN_CLI_PLANNING1`
    FOREIGN KEY (`PLN_JOUR`)
    REFERENCES `mydb`.`PLANNING` (`PLN_JOUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOG_PLN_CLI_LOGEMENT1`
    FOREIGN KEY (`LOG_ID`)
    REFERENCES `mydb`.`LOGEMENT` (`LOG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENT` (
  `CLI_ID` INT NOT NULL AUTO_INCREMENT,
  `CLI_SEXE` VARCHAR(32) NULL,
  `CLI_NOM` CHAR(32) NULL,
  `CLI_PRENOM` VARCHAR(32) NULL,
  `CLI_ENSEIGNE` VARCHAR(100) NULL,
  PRIMARY KEY (`CLI_ID`),
  CONSTRAINT `fk_CLIENT_LOG_PLN_CLI1`
    FOREIGN KEY (`CLI_ID`)
    REFERENCES `mydb`.`LOG_PLN_CLI` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMAIL` (
  `EML_ID` INT NOT NULL AUTO_INCREMENT,
  `CLI_ID` INT NOT NULL,
  `EML_ADRESSE` VARCHAR(100) NULL,
  `EML_LOCALISATION` VARCHAR(65) NULL,
  PRIMARY KEY (`EML_ID`, `CLI_ID`),
  INDEX `fk_EMAIL_CLIENT_idx` (`CLI_ID` ASC),
  CONSTRAINT `fk_EMAIL_CLIENT`
    FOREIGN KEY (`CLI_ID`)
    REFERENCES `mydb`.`CLIENT` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TELEPHONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TELEPHONE` (
  `TEL_ID` INT NOT NULL AUTO_INCREMENT,
  `CLI_ID` INT NOT NULL,
  `TEL_TYPE` VARCHAR(45) NULL,
  `TEL_NUMERO` CHAR(20) NULL,
  `TEL_LOCALISATION` VARCHAR(65) NULL,
  PRIMARY KEY (`TEL_ID`, `CLI_ID`),
  INDEX `fk_TELEPHONE_CLIENT1_idx` (`CLI_ID` ASC),
  CONSTRAINT `fk_TELEPHONE_CLIENT1`
    FOREIGN KEY (`CLI_ID`)
    REFERENCES `mydb`.`CLIENT` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADRESSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADRESSE` (
  `ADR_ID` INT NOT NULL AUTO_INCREMENT,
  `CLI_ID` INT NOT NULL,
  `ADR_LIGNE1` VARCHAR(45) NULL,
  `ADR_LIGNE2` VARCHAR(45) NULL,
  `ADR_LIGNE3` VARCHAR(45) NULL,
  `ADR_VILLE` CHAR(32) NULL,
  `ADR_PAYS` CHAR(32) NULL,
  PRIMARY KEY (`ADR_ID`, `CLI_ID`),
  INDEX `fk_ADRESSE_CLIENT1_idx` (`CLI_ID` ASC),
  CONSTRAINT `fk_ADRESSE_CLIENT1`
    FOREIGN KEY (`CLI_ID`)
    REFERENCES `mydb`.`CLIENT` (`CLI_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRF_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRF_LOG` (
  `LOG_ID` INT NOT NULL,
  `TRF_LOG_PRIX` DECIMAL(2) NOT NULL,
  `TRF_DATE_DEBUT` DATE NOT NULL,
  PRIMARY KEY (`LOG_ID`, `TRF_LOG_PRIX`, `TRF_DATE_DEBUT`),
  INDEX `fk_TRF_LOG_LOGEMENT1_idx` (`LOG_ID` ASC) ,
  CONSTRAINT `fk_TRF_LOG_LOGEMENT1`
    FOREIGN KEY (`LOG_ID`)
    REFERENCES `mydb`.`LOGEMENT` (`LOG_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TARIF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TARIF` (
  `TRF_DATE_DEBUT` DATE NOT NULL,
  `TRF_TAUX_TAXES` INT NULL,
  `TRF_SERVICES` VARCHAR(45) NULL,
  PRIMARY KEY (`TRF_DATE_DEBUT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIGNE_FACTURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIGNE_FACTURE` (
  `LGN_FAC_ID` INT NOT NULL AUTO_INCREMENT,
  `FCT_ID` INT NOT NULL,
  `LGN_FAC_QTE` INT NULL,
  `LGN_FAC_REMISE_POURCENT` INT NULL,
  `LGN_FAC_REMISE_MONTANT` DECIMAL(2) NULL,
  `LGN_FAC_MONTANT` DECIMAL(2) NULL,
  `LGN_FAC_TAUX_TVA` DECIMAL(2) NULL,
  PRIMARY KEY (`LGN_FAC_ID`, `FCT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FACTURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FACTURE` (
  `FCT_ID` INT NOT NULL AUTO_INCREMENT,
  `CLI_ID` INT NOT NULL,
  `FCT_PAIMENT_MDE` VARCHAR(65) NULL,
  `FCT_DATE` DATE NULL,
  `FCT_PAIEMENT_DATE` DATE NULL,
  PRIMARY KEY (`FCT_ID`, `CLI_ID`))
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
