-- MySQL Script generated by MySQL Workbench
-- Thu Feb 27 19:31:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ARTICLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ARTICLE` (
  `ID_ARTICLE` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(80) NULL,
  `Prix HT` FLOAT NULL,
  `Prix TTC` FLOAT NULL,
  `TVA` FLOAT NULL,
  `ISBN` INT NULL,
  `Référence interne 1` VARCHAR(45) NULL,
  `Référence interne 2` VARCHAR(45) NULL,
  `Stock` INT NULL,
  `Date de parution` DATE NULL,
  `Type` VARCHAR(15) NULL,
  PRIMARY KEY (`ID_ARTICLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDEUR` (
  `ID_VENDEUR` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(80) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Email` VARCHAR(35) NULL,
  `Telephone` INT NULL,
  `Type` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_VENDEUR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AUTEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AUTEUR` (
  `ID_AUTEUR` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(80) NULL,
  `Prenom` VARCHAR(45) NULL,
  `IBAN/BIC` VARCHAR(50) NULL,
  `Numero de securite sociale` INT NULL,
  `Numero de SIRET` INT NULL,
  `Association professionnelle` VARCHAR(45) NULL,
  `Telephone` INT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_AUTEUR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONTRAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CONTRAT` (
  `ID_CONTRAT` INT NOT NULL AUTO_INCREMENT,
  `ARTICLE_ID_ARTICLE` INT NOT NULL,
  `AUTEUR_ID_AUTEUR` INT NOT NULL,
  `numero_contrat` INT NULL COMMENT 'Pas l\'ID parce que applicable à plus d\'une ligne si avenants.',
  `Pourcentage 1` FLOAT NULL,
  `Pourcentage 2` FLOAT NULL,
  `Pourcentage 3` FLOAT NULL,
  `Type_droits` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_CONTRAT`, `ARTICLE_ID_ARTICLE`, `AUTEUR_ID_AUTEUR`),
  INDEX `fk_ARTICLE_has_AUTEUR_AUTEUR1_idx` (`AUTEUR_ID_AUTEUR` ASC) VISIBLE,
  INDEX `fk_ARTICLE_has_AUTEUR_ARTICLE_idx` (`ARTICLE_ID_ARTICLE` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICLE_has_AUTEUR_ARTICLE`
    FOREIGN KEY (`ARTICLE_ID_ARTICLE`)
    REFERENCES `mydb`.`ARTICLE` (`ID_ARTICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLE_has_AUTEUR_AUTEUR1`
    FOREIGN KEY (`AUTEUR_ID_AUTEUR`)
    REFERENCES `mydb`.`AUTEUR` (`ID_AUTEUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTE` (
  `ID_VENTE` INT NOT NULL AUTO_INCREMENT,
  `ARTICLE_ID_ARTICLE` INT NULL,
  `VENDEUR_ID_VENDEUR` INT NULL,
  PRIMARY KEY (`ID_VENTE`, `ARTICLE_ID_ARTICLE`, `VENDEUR_ID_VENDEUR`),
  INDEX `fk_ARTICLE_has_VENDEUR_VENDEUR1_idx` (`VENDEUR_ID_VENDEUR` ASC) VISIBLE,
  INDEX `fk_ARTICLE_has_VENDEUR_ARTICLE1_idx` (`ARTICLE_ID_ARTICLE` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICLE_has_VENDEUR_ARTICLE1`
    FOREIGN KEY (`ARTICLE_ID_ARTICLE`)
    REFERENCES `mydb`.`ARTICLE` (`ID_ARTICLE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLE_has_VENDEUR_VENDEUR1`
    FOREIGN KEY (`VENDEUR_ID_VENDEUR`)
    REFERENCES `mydb`.`VENDEUR` (`ID_VENDEUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAIEMENT_DROITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAIEMENT_DROITS` (
  `ID_PAIEMENT` INT NOT NULL AUTO_INCREMENT,
  `VENTE_ID_VENTE` INT NOT NULL,
  `VENTE_ARTICLE_ID_ARTICLE` INT NOT NULL,
  `VENTE_VENDEUR_ID_VENDEUR` INT NOT NULL,
  `AUTEUR_ID_AUTEUR` INT NULL,
  `Date` DATETIME NULL,
  `Montant_vente` FLOAT NULL,
  `Bonus` FLOAT NULL COMMENT 'Si mentionné dans contrat: si vente supérieure à X, bonus de Y.',
  `Montant_total` FLOAT NULL,
  PRIMARY KEY (`ID_PAIEMENT`, `VENTE_ID_VENTE`, `VENTE_ARTICLE_ID_ARTICLE`, `VENTE_VENDEUR_ID_VENDEUR`, `AUTEUR_ID_AUTEUR`),
  INDEX `fk_VENTE_has_AUTEUR_AUTEUR1_idx` (`AUTEUR_ID_AUTEUR` ASC) VISIBLE,
  INDEX `fk_VENTE_has_AUTEUR_VENTE1_idx` (`VENTE_ID_VENTE` ASC, `VENTE_ARTICLE_ID_ARTICLE` ASC, `VENTE_VENDEUR_ID_VENDEUR` ASC) VISIBLE,
  CONSTRAINT `fk_VENTE_has_AUTEUR_VENTE1`
    FOREIGN KEY (`VENTE_ID_VENTE` , `VENTE_ARTICLE_ID_ARTICLE` , `VENTE_VENDEUR_ID_VENDEUR`)
    REFERENCES `mydb`.`VENTE` (`ID_VENTE` , `ARTICLE_ID_ARTICLE` , `VENDEUR_ID_VENDEUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTE_has_AUTEUR_AUTEUR1`
    FOREIGN KEY (`AUTEUR_ID_AUTEUR`)
    REFERENCES `mydb`.`AUTEUR` (`ID_AUTEUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
