-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 09:53:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`family` (
  `product_family_id` INT NULL,
  `product_family_name` VARCHAR(45) NULL,
  PRIMARY KEY (`product_family_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `product_price` DECIMAL(9,2) NULL,
  `product_family_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `product_family_id`),
  INDEX `product_family_id_idx` (`product_family_id` ASC) VISIBLE,
  CONSTRAINT `product_family_id`
    FOREIGN KEY (`product_family_id`)
    REFERENCES `mydb`.`family` (`product_family_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer_country` (
  `customer_country_id` INT NOT NULL,
  `customer_country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customer_id` INT NOT NULL,
  `customer_name` VARCHAR(45) NULL,
  `customer_country_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `customer_country_id`),
  INDEX `customer_country_id_idx` (`customer_country_id` ASC) VISIBLE,
  CONSTRAINT `customer_country_id`
    FOREIGN KEY (`customer_country_id`)
    REFERENCES `mydb`.`customer_country` (`customer_country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`level_one_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`level_one_sale` (
  `level_one_sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `date` DATETIME NULL,
  `customer_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`level_one_sale_id`, `product_id`, `customer_id`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distributor_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distributor_country` (
  `distributor_country_id` INT NOT NULL,
  `distributor_country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`distributor_country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`distributor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`distributor` (
  `distributor_id` INT NOT NULL,
  `distributor_name` VARCHAR(45) NULL,
  `distributor_country_id` INT NOT NULL,
  PRIMARY KEY (`distributor_id`, `distributor_country_id`),
  INDEX `distributor_country_id_idx` (`distributor_country_id` ASC) VISIBLE,
  CONSTRAINT `distributor_country_id`
    FOREIGN KEY (`distributor_country_id`)
    REFERENCES `mydb`.`distributor_country` (`distributor_country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`level_two_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`level_two_sale` (
  `level_two_sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `distributor_id` INT NOT NULL,
  `date` DATETIME NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`level_two_sale_id`, `product_id`, `distributor_id`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  INDEX `distributor_id_idx` (`distributor_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `distributor_id`
    FOREIGN KEY (`distributor_id`)
    REFERENCES `mydb`.`distributor` (`distributor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventory_level_one`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventory_level_one` (
  `inventory_level_one_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`inventory_level_one_id`, `product_id`),
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
